---
title: "What Can We Do to Stop Rat Race in China's Labor Market"
description: "Productivity and Individual Utility - A Chicken and Egg Problem"
author:
  - name: Liwei Jiang
    url: https://samanthacsik.github.io/
    orcid: 0009-0004-3530-8862
    affiliation: Master of Public Policy Program @ Sanford School of Public Policy, Duke University
date: 03-10-2023
categories: [Economic Development, Labor Market] # self-defined categories
citation: 
  url: https://samanthacsik.github.io/
  #use links
# image:  # file name of the picture, the picture should live in this subdirectory
draft: false # setting this to `true` will prevent your post from appearing
---

# Summary

Rat race in the labor market is unhealthy and unsustainable to individuals and society as a whole.The abundant labor supply in China contributes to the prevalence of rat race. But there is more than that. To eliminate rat race phenomenon, the government needs to increase the generosity of its social safety net programs and individuals need to change their perception of unemployment. However, the required financial premises and its trade-off between productivity entail further investigation.

### Rat Race in China

Renowned economist John Keynes proposed in his influential book "Economic Possibilities for Our Grandchildren" that average working hours in the 21st century would decrease to 15 hours per week. This optimistic vision was based on the assumption of continued exponential growth in America's productivity. However, despite the validity of his assumption, Keynes' prediction has yet to materialize. Currently, Americans still work an average of 40 hours per week, and often even more. Meanwhile, on the opposite side of the Pacific, the people of China are grappling with the burdensome 996 work schedule (9 am to 9 pm, 6 days a week). Although many despise the rat race, a significant number of individuals in China find themselves actively participating in it. In this article, we will explore the factors contributing to the emergence of the 996 work culture in China and discuss potential solutions from both personal and societal perspectives.

### Why Rat Race Exists

Before delving into the reasons behind the prevalence of the 996 work culture in China, it is helpful to introduce a related sociological concept known as involution. Involution refers to a phenomenon where cultural forms, having reached a definitive stage, continue to develop by becoming internally more complex. American anthropologist Clifford Geertz referenced this concept in his book "Agricultural Involution: the processes of ecological change in Indonesia" in 1963 to explain Indonesia's failure to industrialize. Geertz used involution to describe the situation in Java, where both external economic pressures from Dutch rulers and internal population growth led to [intensification rather than transformative change of its agriculture industry](https://en.wikipedia.org/wiki/Agricultural_Involution).

China's current labor market exhibits similar characteristics. Workers in China face fierce competition for a limited number of positions. In order to survive this intense competition, workers must demonstrate their value to companies. Many workers, sharing similar backgrounds, naturally resort to providing unpaid overtime labor to outperform their peers. Voluntary overtime work is seen as a means to gain an advantage and secure employment. However, given the low barrier for entry to overtime labor, any worker in the market, except those with disabilities, can engage in the same practice. This results in a zero-sum game where more and more workers supply free overtime labor, ultimately leading to the dominance of the 996 culture in society. Companies, being the primary beneficiaries, are enthusiastic about reducing costs by taking advantage of this cutthroat competition among employees, further fueling the popularity of the 996 work schedule.

Undoubtedly, 996 exploits workers. However, it is argued that this extended working time may boost societal productivity at relatively low costs by maximizing the working hours of individuals. This increased productivity aligns with China's economic development goals, which have been prioritized since the country's reform and opening up. This alignment could explain why the Chinese government has not implemented strong measures to suppress the popularity of the 996 culture.

### The Benefits and Harms of 996:

As discussed earlier, the 996 work schedule can initially contribute to increased social productivity by allowing for additional working hours. This boost in productivity may appear favorable due to its low cost compared to other alternatives.

However, it is important to consider the long-term limitations and drawbacks of relying solely on the 996 model. There are essentially two approaches to enhancing productivity: increasing working hours or leveraging technology advancements to improve individual productivity. The potential productivity gains from working longer hours are inherently limited by the fixed 24-hour day. Thus, the scope for productivity growth through extended work hours is ultimately constrained. In contrast, technology development offers the potential for limitless productivity growth. Since the first industrial revolution, [global GDP](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?end=2021&start=1960&view=chart) has skyrocketed from USD 1.2 trillion in 1820 to USD 95 trillion in 2022. The exponential increase in individual and social productivity since then has far surpassed the progress made by humanity over millions of years before that. Consequently, relying on involution (such as the 996 schedule) to drive productivity is akin to quenching thirst by drinking poison. Overreliance on extended work hours can impede investment in technology development, which may eventually trap developing countries like China in a middle-income trap, as experienced by Java.

Moreover, the poor work-life balance associated with the 996 schedule significantly reduces workers' leisure time, which can undermine their creativity and limit their opportunities for personal consumption. Insufficient time for relaxation and rest can lead to physical and mental fatigue, suppressing creativity and negatively impacting workers' mental well-being. Additionally, the 996 schedule can impede individual consumption of goods, thereby slowing down economic development by limiting the flow of money into the tertiary industry, which typically yields high added value.

### How to Eliminate 996?

Eliminating the phenomenon of "involution" needs to be considered from both individual and societal perspectives. At the individual level, it is crucial for workers to recognize that the cultivation of an involutionary culture is an unsustainable mode of development. Involution brings limited and cheap competitive advantages to individuals but comes at the cost of mental and physical burdens. Furthermore, involution suppresses opportunities for individuals to pursue diversified development, and this opportunity cost is difficult to compensate for with the competitive advantages gained from involution. When individuals deeply understand the negative impacts of involution, it provides a fertile ground for resistance against involution and offers the possibility of broader awakening and resistance.

The complete eradication of involution requires more efforts from the government and society. Economically, the reservation wage of workers and the isocost curves of companies determine the form of labor (working hours and wages) for workers. The reservation wage ($RW$) is primarily composed of the following factors: unemployment assistance provided by the government ($U$), the duration period being unemployed ($D$), and the psychological pressure caused by unemployment ($P$). The specific function is as follows:

$RW=U-D-P$

Therefore, enhancing unemployment assistance, reducing the difficulty of reemployment, and alleviating the psychological pressure caused by unemployment are the main ways to improve the reservation wage of workers. Let's focus on addressing the challenges of reemployment and the psychological pressure caused by unemployment first.

#### *Reduce the Difficulty of Reemployment:*

Reducing the duration period under unemployment is primarily the responsibility of the government. Firstly, there is a need for an adequate number of available job positions in society. This necessitates the development of the private economy. In today's society, the majority of job positions are provided by private enterprises. During the COVID-19 pandemic, private enterprises across the country were greatly affected, leading to the current high unemployment rate. Supporting private enterprises in recovering from the impact of the pandemic, reducing social investment risks, and helping them expand their investments are among the methods to increase available employment opportunities and reduce the difficulty of reemployment in society.

Another method is to enhance the vocational skills of workers. The transformation of China's manufacturing industry from low-end to high-end will inevitably squeeze the employment space for workers with low vocational skill levels. The industrial systems of automation and mechanization will increasingly require workers with skills such as operating machinery and troubleshooting. The demand for low-skilled labor that performs repetitive tasks on production lines will decrease. However, the low-skilled labor force, mainly composed of migrant workers, remains the mainstay of China's job market. [The number of migrant workers in China](http://www.gov.cn/xinwen/2022-12/30/content_5734175.htm) has grown from 260 million in 2012 to 290 million in 2021. It is unrealistic to rely on the initiative of migrant workers to engage in large-scale learning to improve their vocational skills, as this group faces serious resource and information constraints. Firstly, extensive physical labor during the day makes it difficult for workers to have the energy and time for further learning. Secondly, facing a complex and diverse job market, migrant workers struggle to obtain reliable information to determine which vocational skills are in demand and which skills are suitable for them. Moreover, even if migrant workers successfully identify the vocational skills required by the market and suitable for themselves, they face difficulties in finding effective channels for learning. It is worth noting that even though there are a large number of vocational skill teaching videos available on the internet, such as programming, data analysis, and CNC machines, migrant workers may not have access to these resources. Based on my personal experience, a considerable number of migrant workers aged between 40 and 50 do not have Wi-Fi installed in their residences, and their smartphones may not be capable of viewing online videos. Finally, the opportunity cost of time spent on learning vocational skills can also hinder workers' ability to engage in learning. Workers can utilize that time for more labor to earn higher wages. The wages forgone due to the time spent on learning vocational skills represent the opportunity cost. For some workers living near the poverty line, these opportunity costs may be highly tempting or insurmountable.

Therefore, the large-scale improvement of labor skills relies on the government's formulation of relevant policies. The Chinese government has already recognized this, as stated in [the report of the 20th Party Congress](http://www.gov.cn/xinwen/2022-12/30/content_5734175.htm), which emphasizes "enhancing skills and increasing employment as the most effective and direct means of poverty alleviation, providing support in terms of funds, policies, and services." During the three-year action plan for vocational skills improvement from 2019 to 2021, the government allocated 100 billion CNY from the surplus of the unemployment insurance fund. Through various forms, they provided subsidized vocational skills training to more than 83 million individuals, continuously enhancing the stability of employment and the ability to transition to different positions for workers. However, it is important to note that over 83 million training participations do not necessarily mean that over 83 million individuals received vocational skills training. Therefore, the government still needs to invest more resources in vocational skills training.

Furthermore, the government should also strive to improve conditions for self-learning among workers. Increasing the coverage of the internet, free Wi-Fi access, and smart devices can effectively help workers access a wealth of free resources and information online, enabling them to engage in vocational skills learning more flexibly.

#### *Reduce the Mental Pressure of Unemployment:*

This is connected to the changes at the individual level mentioned earlier. The psychological pressure of unemployment often stems not only from the financial stress of having no source of income but also from society's negative perception of unemployment. Society often defines unemployment as a personal failure, a denial of individual value, especially in China. The negative attitudes towards unemployment from the surrounding individuals can influence the unemployed person's perception of their own status and value through various social interactions. It is essential to make society aware that unemployment is often not due to the individual's lack of abilities but rather the mismatch between personal skills and job requirements, as well as poor management by companies. Taking a proactive approach to unemployment and viewing it as an opportunity to get a fresh start and find a suitable position can effectively reduce the psychological pressure of unemployment and subsequently enhance the reservation wage of workers.

#### *Increase Unemployment Assistance:*

*Increasing unemployment assistance is the most direct way to improve workers' reservation wage. This increase should not only reflect in the amount of unemployment insurance and subsidies that can be received but also in continuously reducing the difficulty of application and expanding the coverage*. It is important to make more workers aware of, participate in, and receive unemployment assistance. Both of these points are reflected in current policies in China.

Currently, there are two main forms of unemployment assistance in China: unemployment insurance and unemployment relief funds. Unemployment insurance is a social insurance system funded by the government and jointly contributed to by enterprises and employees.

Currently, there are [238 million employees](http://www.news.cn/2023-01/23/c_1129308986.htm) participating in unemployment insurance nationwide. Insured workers can apply to the government for unemployment insurance benefits within the specified time after becoming unemployed. Unemployment relief funds are supplementary to unemployment insurance and cover groups temporarily not covered by unemployment insurance.

In May 2022, the Ministry of Human Resources and Social Security, the Ministry of Finance, and the State Taxation Administration issued the "[Notice: Do a Good Job in Stable Employment, Skills Enhancement, and Unemployment Prevention through Unemployment Insurance.](http://www.gov.cn/fuwu/2022-05/18/content_5690958.htm)" The notice states that the expansion policy of unemployment insurance coverage will continue, and unemployment relief funds will be provided to unemployed individuals who have completed the period for receiving unemployment insurance benefits but are still unemployed, as well as insured unemployed individuals who do not meet the conditions for receiving unemployment insurance benefits. Temporary living allowances will be provided to unemployed rural migrant workers who have been insured for less than one year.

In addition, the notice requires each province (autonomous region, municipality directly under the central government) to gradually increase the unemployment insurance benefit standard to 90% of the local minimum wage based on local conditions. It also emphasizes the need to further streamline the national online application process for unemployment insurance benefits, making it easier for unemployed individuals to apply.

### Eliminating the Contradiction between Overwork and Social Productivity: the Chicken and Egg Problem

We have discussed numerous methods to improve workers' reservation wage, but all of these methods undoubtedly require increased government financial expenditure. Fiscal expenditure relies on fiscal revenue, and social productivity represents the government's ability to generate fiscal revenue. Therefore, without a solid foundation of productivity, even the best policy recommendations cannot be effectively implemented.

Eradicating 996 requires strong support from social productivity, yet the existing social productivity is, to a certain extent, based on overwork itself. For example, increasing unemployment assistance requires greater financial investment, but increased financial investment depends on a continuous rise in fiscal revenue. Some may argue that the long working hours resulting from overwork have enhanced China's social productivity and, consequently, increased the Chinese government's fiscal revenue. Thus, eliminating overwork can impact social productivity, and the decline in social productivity can affect the government's ability to eliminate overwork. For developing countries facing unfavorable economic conditions, education is a means to improve social productivity. However, based on the current backward state of social productivity, the limited fiscal revenue of these countries may not be sufficient to support significant investments in education. Increasing productivity requires education, and education requires high productivity. This is the chicken and egg problem.

However, does a decrease in working hours necessarily imply a decline in social productivity? The answer is no. First, having more leisure time means that workers have more time to engage in consumption, which stimulates economic growth. Moreover, having more leisure time allows workers to rest adequately and enhance their vocational skills, thereby effectively improving productivity. [Two randomized trials conducted in Iceland](https://www.vox.com/22568452/work-workweek-five-day-four-jobs-pandemic) provide evidence for this. The experiments took place in 2015 and 2017, where workers' weekly working hours were reduced from 40 to 35-36 hours while keeping their salaries unchanged. Participants reported achieving a better work-life balance, reduced work-related stress, and improved quality of life. Surprisingly, during the experiments, workers and managers collaboratively explored ways to increase work efficiency and reduce working hours, ensuring that productivity remained unchanged or even increased.

There is no doubt that the development brought by rat race (996) is unsustainable. Eliminating overwork benefits both individuals and society. While government policy-making is undoubtedly important, we must also realize that our own perception of overwork has a significant impact on its eradication. Actively improving our vocational skills, changing our attitudes towards unemployment, and refusing to participate in the destructive competition of overwork can expedite our society's departure from overwork and truly usher in a stage of healthy development.
