---
title: "为什么内卷和怎么消灭内卷"
description: "一个先有鸡还是先有蛋的问题"
author:
  - name: 姜力维
    url: https://github.com/CastDown/CastDown.github.io
    orcid: 0009-0004-3530-8862
    affiliation: Master of Public Policy Program @ Sanford School of Public Policy, Duke University
date: 03-27-2023
categories: [Economic Development, Labor Market] # self-defined categories
citation: 
  url: https://github.com/CastDown/CastDown.github.io
  #use links
# image:  # file name of the picture, the picture should live in this subdirectory
draft: false # setting this to `true` will prevent your post from appearing
---

### 内卷现象的观察

1930年，著名经济学家约翰凯恩斯在他的论文《Economic Possibilities for Our Grandchildren》中预测到，人们在21世纪或将只需要每周工作15个小时。这一美好的愿景更多是基于对于美国社会的预测，基于美国本身就发达生产力仍将继续不断发展的假设。然而，现如今看来，假设成立，但是结果却并未和预期一样出现。如今美国人仍然每周工作40小时，甚至更多。而我们更是挣扎在996的内卷"福报"中。人人都痛恨内卷，而很多痛恨内卷的人仍在疯狂内卷。这篇文章我们将探讨是什么因素导致了内卷的产生，以及哪些措施可以从个人以及政府社会的角度消灭内卷。

### 为什么会内卷

在聊我们的社会为什么会这么卷之前，我想先岔开一下，聊一下内卷一次的由来。我们现在使用内卷形容以"自愿"996为代表的恶性竞争，过度竞争等社会行为。内卷（Involution）在社会学中本身用来形容某文化模式达到某最终形态后，无法自我稳定，也无法转变为新的形态，只能使自己在内部更加复杂化。1963年，美国人类学家克利福德·格尔茨在他的书籍《[**农业的内卷化：印度尼西亚生态变迁的过程**》](https://en.wikipedia.org/wiki/Agricultural_Involution)中使用内卷化来解释印度尼西亚的工业化失败。这本书提到1830年之后的爪哇并未利用工业化来应对人口增长以及帝国主义的挑战，反而不断复杂化其水稻种植的土地使用、租佃关系、劳动力安排等方面。这种农业系统的内卷化进而导致了其工业化的失败。

首先我们从个人角度来理解这个问题。利用博弈论的观点，劳动市场上的每个个体都在与想类似的个体竞争*极其有限、供不应求*的就业岗位。相互的博弈就必然导致个体之间需要通过一定的方式展现自己对于公司的价值。当一切的背景能力都相同或非常接近的情况下，相当一部分个体便自然而然地希望通过自愿加班来展现自己对于公司的价值，进而击败竞争对手，来保护自己的就业岗位。但因为自愿加班的门槛非常低，除了身体无法长期工作的人群或者内心无比厌恶超时工作的人群以外，劳动市场内的所有的人都可以完成。于是当少数一部分个体开始利用自愿加班来争夺极其有限、供不应求的就业岗位的时候，剩下的个体便被迫参与到这种零和博弈中来，最终导致了996文化的盛行。公司作为天然的受益者更会利用雇员之间的非良性竞争来压缩成本，并放任996文化的兴盛。

从社会政府方面，996文化固然是对于劳动者权益的践踏。但996可能为社会带来的是低成本的生产力增加。996可以通过延长劳动者的劳动时间来达到以有限的成本放大有限的个体的生产力的目的。这种生产力的提升可以帮助我国快速提升生产力，所以十分契合我国改革开放初期后强调经济发展的政策。这也可能就是996文化虽然盛行，但是我国政府并未直接通过立法等方式抑制该文化的原因。

### 内卷的好处与危害？

内卷所带来的工作时间的提升可以提升社会的整体生产力。且其廉价性（免费加班）使得这种生产力的提升具有较低的成本，并更容易受到资本的喜爱。·

但这种生产力的提升的上限非常低。社会生产力的提升简单来说具有两种形式，一是简单的工作时间的增加，二是科技的发展以及个人单位生产力的提升。简单的工作时间的增加的上限就是时间的上限，即24小时。所以即使内卷的终极形式，也只能为社会带来每个劳动者工作24小时的生产力，这个上限是固定的，无法突破的。然后科技的发展以及个人单位生产力的提升则难以设置上限。自工业革命以来，[人类社会的GDP](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?end=2021&start=1960&view=chart)从1820年的约1.2万亿美元增长到的2022年的95万亿美元。工业革命的科技发展所带来的社会整体生产力以及单位个人生产力的提升远远超过自人类诞生到工业革命之前的几百万年间的发展。因此，内卷所带来的生产力提升对于社会更像是饮鸩止渴。对于低成本的生产力提升的依赖可能会延缓社会对于科技发展的投资，最终使得发展中国家落入中等收入陷阱，就如同爪哇一般。而这对于我国来说犹是如此。

此外， 加班内卷所导致的休息生活时间的减少也可能降低个人的创造力并且减少了个体消费的机会。休息时间的不足使得工作的个人难以从过量工作的疲劳中恢复过来。身体以及精神的疲劳难以避免地抑制劳动者的创造力，进而降低了劳动者的生产力。过度的疲劳也会对于劳动者的精神状态产生巨大的负面影响，这可能也解释了近代美国罹患抑郁症概率的提升有关。在内卷的过量劳动的疲惫的作用下，劳动者倾向于选择公司到家的两点一线的生活方式。这种生活方式减少了个人消费的机会。消费水平的降低会减缓具有高附加值的第三产业的发展，进一步阻止社会的经济发展。

### 怎么可以消灭内卷？

消灭内卷要从个人以及社会两个层面来考虑。个人层面，更多的是劳动者需要意识到滋长内卷文化是不可持续的发展方式。内卷对于个人带来的是有限且廉价的竞争优势，但是伴随着精神、身体的双重负担。此外，内卷更抑制了个人追寻多元发展的机会，这种机会成本是内卷带来的竞争优势所难以弥补的。当个人深刻地意识到了内卷的负面影响，对于内卷的抵抗就有了滋生的土壤，也为更大范围的觉醒并且抵抗提供了可能。

内卷的彻底消灭，更多需要政府以及社会层面的力量。经济学上，劳动者的reservation wage以及公司的isocost curves决定了劳动者的劳动形式（工作时长以及工资）。其中 reservation wage主要由组成：政府提供的失业救助、再就业所需时长、以及失业所带来的精神压力。具体公式为：

所以，提升失业救助、降低再就业难度、降低失业精神压力是提升劳动者的reservation wage的主要方式。我们首先关注再就业难度以及失业精神压力。

#### *降低再就业难度：*

降低再就业所需时长主要是政府职责。首先，社会上需要有足够的就业岗位提供给劳动者。这也就需要私有经济的发展。在当今社会，大部分的就业岗位是由私营企业所提供的。在新冠疫情期间，全国各地的私营企业收到了巨大了影响，这也导致了现在的高失业率。扶持私营企业尽快从疫情的影响中恢复过来，降低社会投资风险，帮助私营企业扩大投资，是为社会增加就业岗位、降低再就业难度的方法之一。

另一个方法则是提升劳动者的职业技能水平。当今我国从低端制造业到高端制造业的转型将会无法避免的挤压低职业技能水平的劳动者的就业空间。自动化、机械化的工业体系将会更加需要拥有操控机器、排除故障等技能的劳动者。对于在生产线上重复单一劳动的低端劳动力的需求将会降低。但是主要由进城务工人员所组成的低端劳动力仍是我国就业市场的主力军，在我国，[农民工数量](http://www.gov.cn/xinwen/2022-12/30/content_5734175.htm)由2012年的2.6亿增长到了2021年的2.9亿。寄希望于农民工群体主动大规模地进行学习以提升自己的职业技能是不切实际的，因为农民工群体面临着严重的资源以及信息限制。首先，白天大量的体力劳动导致劳动者很难在空余时间再有精力进行学习。其次，面对纷繁复杂的就业市场，农民工难以获取有效的信息来判断哪些职业技能是市场所需要的以及那些职业技能是适合自己的。另外，即使农民工有效判断出了市场所需且适合自己的职业技能，农民工也难以寻找有效的渠道进行学习。值得注意的是，即使目前网络上有大量的职业技能教学视频，例如编程、数据分析、数控机床，农民工并不一定具有接触到这类职业技能教学视频的机会。根据我的亲身经历，相当一部分年龄在40-50岁的进城务工者在居住地并未安装Wifi，且他们的手机并不一定是可以在线观看视频的智能机。最后，学习职业技能所需时间的机会成本也会阻碍劳动者进行学习。劳动者可以利用学习时间进行更多的劳动来赚取更多的工资。由于学习职业技能所放弃的这部分工资就是学习职业技能的时间的机会成本。而这些机会成本对于一些生活在贫困线附近的劳动者来说，可能是极具诱惑力或者是不可逾越的。

于是，大规模提升劳动技能水平则要依靠政府制定相关的政策。我国政府已经注意到了这一点，[党的二十大报告](http://www.gov.cn/xinwen/2022-12/30/content_5734175.htm)中就提到了"把提升技能、增加就业作为最有效最直接的脱贫方式，从资金、政策、服务等方面给予倾斜支持"。 在2019---2021年的职业技能提升三年行动中，政府从失业保险基金结余中拿出了1000亿元，采取多种形式，累计开展补贴性职业技能培训8300多万人次，劳动者稳定就业和转换岗位能力不断增强。不过值得注意的是，8300多万人次并不代表8300多万人接受了职业技能培训，所以我们政府仍需要更多的资源投入在职业技能培训当中。

此外，政府也应致力于进一步改善劳动者自我学习的条件。提升网络以及免费wifi的覆盖率，提升智能设备的覆盖率也可以有效帮助劳动者接触到网络上大量的免费资源以及信息，帮助劳动者更加灵活地进行职业技能学习。

#### *降低失业精神压力：*

这和前面提到的个人层面的改变是一体的。失业精神压力往往不仅来源于没有收入来源所带来的金钱压力，也来自于社会对于失业的负面定义。社会往往对于失业的定义是个人的失败，是对个人价值的否定，尤其是在我们国家。人是一切社会关系的总和，所以周遭的人对于失业的负面态度会通过各种社会关系影响到失业者对于自身状态以及价值的态度。如何让社会意识到往往失业并不是由于失业者自身能力的不足，更多是由于个人技能与岗位需求的不匹配和公司的不善经营所导致的。积极面对失业并将失业视为自己重新开始寻找适合自己的岗位的机会可以有效地降低失业所带来的精神压力，进而提升劳动者的reservation wage。

#### *提高失业救助：*

提高失业救助是最直接的提升劳动者reservation wage的方式。这一提高应不仅体现在失业保险金、补助金的可领取金额上，也应体现于不断降低申请难度，提高覆盖范围。让更多的劳动者知晓、参与并且领取到失业救助。这两点在我国目前的政策中都有所体现。

目前我国的失业救助主要有两种形式，失业保险金以及失业救助金。我国的失业保险是由政府出资、企业和职工共同缴纳的社会保险制度，目前全国有[2.38亿](http://www.news.cn/2023-01/23/c_1129308986.htm)职工参加了失业保险。被保险的劳动者可以在失业后的规定时间内向政府申请领取失业保险金。失业补助金是失业保险的补充项目，用来覆盖失业保险暂时无法覆盖的人群。2022年5月，人力资源社会保障部、财政部、国家税务总局印发[《关于做好失业保险稳岗位提技能防失业工作的通知》](http://www.gov.cn/fuwu/2022-05/18/content_5690958.htm)。《通知》指出继续实施失业保险保障扩围政策，对领取失业保险金期满仍未就业的失业人员、不符合领取失业保险金条件的参保失业人员，发放失业补助金；对参保不满1年的失业农民工，发放临时生活补助。此外，《通知》要求各省（自治区、直辖市）要根据本地实际，逐步将失业保险金标准提高至最低工资标准的90%，并且要进一步优化失业保险待遇全国线上申领统一入口，方便失业人员申领。

### 消灭内卷与社会生产力的矛盾：先有鸡还是先有蛋？

我们提到的众多可以提升劳动者 reservation wage的方法，但是这些方法都毫无例外的需要政府更多的财政支出。财政支出需要财政收入，而社会生产力就代表了政府财政收入的能力。所以，没有良好的生产力基础，再好的政策建议都无法落地执行。消灭内卷需要强大社会生产力的支持，而现有的社会生产力又在一定程度上是基于内卷的。举例来说，提失业救助需要更大的财政投入，但是更大的财政投入需要建立在不断提升的财政收入。而有些人则可能认为内卷所带来的长工作时间提升了我国的社会生产力，进而为政府提高了财政收入。所以消灭内卷会影响社会生产力，而降低的社会生产力则会影响政府消灭内卷的能力。对于经济状况不利于我们的发展中国家来说，教育是提高社会生产力的方法，但是在现有落后的社会生产力的基础上，这些国家的政府有限的财政收入可能并不足以支持在教育领域的大力投资。提高生产力需要教育，教育需要高生产力。这就是先有鸡还是先有蛋的问题。

但其实，所带来的工作时长的降低是否就一定意味着社会生产力的降低呢？答案是否定的。首先，更多的业余时间意味着劳动者有更多的时间在社会中进行消费，拉动经济增长。且更多的业余时间导致劳动者可以充足的休息并且进行职业技能的提升，进而更加有效的提高生产力。在冰岛的两项[随机试验](https://www.vox.com/22568452/work-workweek-five-day-four-jobs-pandemic)就表明，更多的劳动时间并不会降低公司/劳动者的生产力，甚至会提升生产力。

两项随机试验分别发生在2015年及2017年。在实验中，在薪资不变的情况下，劳动者每周的工作时间从40小时减少到35到36小时。实验对象都表明自己有了更好的工作生活之间的平衡，工作压力有所降低并且生活质量有所提升。且令人惊讶的是，在实验过程中，劳动者与管理者们通过相互合作共同探索了提升工作效率、降低工作时长的方法，进而保证生产力的不变甚至是提升。

毫无疑问，内卷所带来的发展是不可持续的。消灭内卷对于个人以及社会都有所裨益。政府的政策制定固然重要，但我们也要意识到我们自己对于内卷的认知对于消灭内卷也有巨大的影响。主动提升自己的职业技能、转变自己对于失业的态度、拒绝参与到内卷的恶行竞赛中，这都可以让我们的社会更快的告别内卷，真正迎来良性发展的阶段。
